# Mini-Lesson 14.2: Data Types, Classes, Objects, and Packages in Java

## Overview

This lesson expands on several core Java concepts:

- Java architecture
- Data types
- Type casting
- Data type hierarchy
- Classes
- Objects
- Packages

These concepts form the foundation of Java programming and object-oriented development.

---

# What Is Java?

Java is a:

- Class-based programming language
- Object-oriented programming (OOP) language
- Compiled language
- Platform-independent language

One of Java's primary goals is:

> Write Once, Run Anywhere (WORA)

---

# How Java Works

Unlike Python, which is generally interpreted, Java follows a compilation process.

## Step 1: Write Source Code

Example:

```java
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
```

Saved as:

```text
HelloWorld.java
```

---

## Step 2: Compile

The Java compiler converts source code into bytecode.

```bash
javac HelloWorld.java
```

Output:

```text
HelloWorld.class
```

---

## Step 3: Bytecode Verification

The Java Virtual Machine (JVM) validates the generated bytecode.

---

## Step 4: Execute

The JVM converts bytecode into machine-specific instructions.

```bash
java HelloWorld
```

---

# Java Architecture

```text
Java Source Code (.java)
          |
          V
Java Compiler (javac)
          |
          V
Bytecode (.class)
          |
          V
Java Virtual Machine (JVM)
          |
          V
Machine Code
```

---

# Platform Independence

Java applications are platform-independent because:

- Source code is compiled into bytecode.
- Bytecode runs on the JVM.
- Different operating systems have their own JVM implementations.

Examples:

- Windows JVM
- Linux JVM
- macOS JVM

This allows the same Java application to run across platforms.

---

# Java Data Types

Java is a statically typed language.

This means:

- Every variable must have a declared type.
- Variable types cannot change after declaration.
- The compiler knows how data should be handled.

Example:

```java
int age = 25;
```

Valid:

```java
int age = 25;
```

Invalid:

```java
age = "Twenty Five";
```

---

# Primitive Data Types

Java provides eight primitive data types.

## Byte

Whole numbers.

```java
byte value = 127;
```

Storage:

```text
1 Byte
```

Range:

```text
-128 to 127
```

---

## Short

Whole numbers.

```java
short value = 32000;
```

Storage:

```text
2 Bytes
```

Range:

```text
-32,768 to 32,767
```

---

## Int

Most common integer type.

```java
int value = 100000;
```

Storage:

```text
4 Bytes
```

Range:

```text
-2,147,483,648 to 2,147,483,647
```

---

## Long

Large whole numbers.

```java
long population = 8000000000L;
```

Storage:

```text
8 Bytes
```

---

## Float

Approximate decimal values.

```java
float price = 19.99f;
```

Storage:

```text
4 Bytes
```

Precision:

```text
6-7 digits
```

---

## Double

High-precision decimal numbers.

```java
double salary = 52345.75;
```

Storage:

```text
8 Bytes
```

Precision:

```text
Up to 15 digits
```

---

## Boolean

Stores true or false.

```java
boolean active = true;
```

Possible Values:

```text
true
false
```

---

## Char

Stores a single character.

```java
char grade = 'A';
```

Storage:

```text
2 Bytes
```

Examples:

```text
A
4
#
```

---

# Why Data Types Matter

Consider:

```java
average = (a + b) / 2;
```

Questions arise:

- What if `a` is an integer?
- What if `b` is a double?
- What if one value is a string?

Java avoids ambiguity through strict typing.

---

# Casting

Casting converts one data type into another.

---

## String to Integer

```java
String stringNumber = "12";

int number = Integer.valueOf(stringNumber);
```

Result:

```text
12
```

---

## Integer to String

```java
int number = 12;

String text = String.valueOf(number);
```

Result:

```text
"12"
```

---

# Data Type Hierarchy

When performing calculations, Java promotes data types according to precision.

General hierarchy:

```text
byte
  ↓
short
  ↓
int
  ↓
long
  ↓
float
  ↓
double
```

The result inherits the most precise type involved in the operation.

---

# Examples

## Integer Division

```java
2 / 3
```

Result:

```text
0
```

Reason:

Both operands are integers.

---

## Double Division

```java
2.0 / 3
```

Result:

```text
0.6666667
```

Reason:

One operand is a double.

---

## Integer Zero Division

```java
0 / 3
```

Result:

```text
0
```

---

## Double Zero Division

```java
0 / 3.0
```

Result:

```text
0.0
```

---

# Classes vs Objects

Classes and objects are fundamental to Object-Oriented Programming.

---

# Recipe Analogy

## Class = Recipe

Contains:

- Ingredients
- Instructions

A class defines:

- Variables
- Methods
- Constructors

---

## Object = Finished Dish

An object is:

- A real instance
- Created from a class

Multiple objects can be created from a single class.

---

# Example Class

```java
public class Car {

    String make;
    String model;

}
```

---

# Creating Objects

```java
Car car1 = new Car();
Car car2 = new Car();
```

Each object has its own values.

```java
car1.make = "Toyota";
car2.make = "Ford";
```

---

# Why Classes Matter

Classes provide:

- Reusability
- Modularity
- Organization
- Maintainability

Large applications may contain hundreds or thousands of classes.

---

# Packages

Packages organize related classes.

Without packages, large Java applications would be difficult to manage.

---

# Benefits of Packages

- Better organization
- Reduced complexity
- Code reuse
- Improved maintainability
- Namespace management

---

# Package Structure Example

```text
com.company.hr

├── Employee.java
├── Manager.java
└── Department.java
```

---

# Import Statements

To use classes outside the current package:

```java
import java.util.Scanner;
```

After importing, classes become available within the program.

---

# Cookbook Analogy

Think of a package as a cookbook.

Without page numbers, finding a recipe would be difficult.

Packages provide the location for classes.

Example:

```java
import com.company.hr.Employee;
```

This tells Java where to find the Employee class.

---

# Modularity in Java

Packages help create modular applications.

Benefits:

- Easier debugging
- Easier testing
- Easier collaboration
- Better scalability

This becomes extremely important in enterprise applications.

---

# Key Takeaways

- Java is both compiled and platform-independent.
- Java source code is converted into bytecode.
- The JVM executes bytecode on different operating systems.
- Java uses strict static typing.
- Primitive data types store simple values.
- Casting converts data between types.
- Classes act as blueprints.
- Objects are instances of classes.
- Packages organize related classes and support modular design.
- Import statements allow classes from other packages to be used within a program.

---

# Personal Notes

- Java requires more planning than Python because data types must be declared.
- The JVM is the key reason Java can run on many operating systems.
- Understanding classes and objects is essential before learning Spring Boot.
- Packages help keep enterprise applications organized and maintainable.
- The recipe analogy makes classes and objects much easier to understand.